import { PromptData } from './prompt-builder';

export interface Preset {
    id: string;
    category: 'common' | 'creative' | 'utility';
    icon: string;
    data: Partial<PromptData>;
}

export const presets: Preset[] = [
    // ============ COMMON PRESETS (37) ============

    {
        id: 'studioPortrait',
        category: 'common',
        icon: '📸',
        data: {
            background: 'Simple Gradient',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Rule of Thirds', 'Center Composition'],
            pose: ['Front Facing Portrait', 'Headshot'],
            mood: ['Professional'],
            style: ['Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'editorialFashion',
        category: 'common',
        icon: '👗',
        data: {
            background: 'Fashion Studio',
            lighting: ['Dramatic Lighting', 'High Key Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Dynamic Angles', 'Leading Lines'],
            pose: ['Fashion Pose', 'Editorial Pose'],
            makeup: ['Editorial/High Fashion', 'Glamorous/Full Glam'],
            mood: ['Dramatic', 'Confident'],
            style: ['Fashion Photography', 'Editorial Photography'],
            colorGrading: 'High Contrast',
            addons: ['Highly Detailed', 'Masterpiece', 'Professional Photography'],
        },
    },
    {
        id: 'goldenHour',
        category: 'common',
        icon: '🌅',
        data: {
            background: 'Beach',
            timeOfDay: 'Golden Hour',
            weather: ['Clear'],
            lighting: ['Golden Hour Light', 'Natural Sunlight'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            lightColor: 'Warm Golden',
            mood: ['Romantic', 'Dreamy'],
            style: ['Portrait Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Professional Photography', 'Photorealistic'],
        },
    },
    {
        id: 'productShot',
        category: 'common',
        icon: '📦',
        data: {
            background: 'Pure White',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            lens: ['Macro Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Center Composition', 'Minimalist'],
            mood: ['Clean', 'Professional'],
            style: ['Product Photography', 'Commercial Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Highly Detailed', '8K Resolution'],
        },
    },
    {
        id: 'streetPhotography',
        category: 'common',
        icon: '🏙️',
        data: {
            background: 'Urban City',
            timeOfDay: 'Afternoon',
            lighting: ['Natural Sunlight', 'Available Light'],
            lens: ['35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            composition: ['Leading Lines', 'Rule of Thirds'],
            pose: ['Candid/Natural', 'Walking Pose'],
            mood: ['Authentic', 'Urban'],
            style: ['Street Photography', 'Documentary Photography'],
            colorGrading: 'Urban Grit',
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'blackAndWhite',
        category: 'common',
        icon: '⚫',
        data: {
            background: 'Simple Gradient',
            lighting: ['Dramatic Lighting', 'Rembrandt Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Rule of Thirds', 'Dramatic Framing'],
            mood: ['Dramatic', 'Timeless'],
            style: ['Black and White Photography', 'Fine Art Photography'],
            colorGrading: 'Black and White',
            filmStock: ['Ilford HP5', 'Kodak Tri-X'],
            addons: ['Highly Detailed', 'Sharp Focus', 'Masterpiece'],
        },
    },
    {
        id: 'cinematic',
        category: 'common',
        icon: '🎬',
        data: {
            background: 'Moody Interior',
            lighting: ['Cinematic Lighting', 'Volumetric Lighting'],
            lens: ['Anamorphic Lens'],
            camera: 'Cinema Camera',
            cameraType: 'Cinema Camera',
            composition: ['Widescreen Framing', 'Rule of Thirds'],
            aspectRatio: '21:9 Cinematic',
            mood: ['Cinematic', 'Dramatic'],
            style: ['Cinematic Photography', 'Film Still'],
            colorGrading: 'Cinematic Color Grade',
            specialEffects: ['Lens Flare', 'Film Grain'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'naturalBeauty',
        category: 'common',
        icon: '🌿',
        data: {
            background: 'Natural Outdoors',
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            makeup: ['Natural/No-Makeup Makeup', 'Dewy/Glass Skin'],
            pose: ['Front Facing Portrait', 'Candid/Natural'],
            mood: ['Fresh', 'Natural'],
            style: ['Beauty Photography', 'Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Sharp Focus', 'Photorealistic'],
        },
    },
    {
        id: 'corporateHeadshot',
        category: 'common',
        icon: '💼',
        data: {
            background: 'Neutral Gray',
            lighting: ['Studio Lighting', 'Softbox Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Business Suit', 'Blazer'],
            pose: ['Headshot', 'Front Facing Portrait'],
            action: ['Confident', 'Smiling'],
            mood: ['Professional', 'Confident'],
            style: ['Corporate Photography', 'Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
        },
    },
    {
        id: 'weddingBridal',
        category: 'common',
        icon: '💒',
        data: {
            background: 'Garden',
            lighting: ['Soft Natural Light', 'Backlight'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Wedding Dress'],
            mood: ['Romantic', 'Elegant', 'Dreamy'],
            style: ['Wedding Photography', 'Portrait Photography'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Bokeh', 'Soft Glow'],
            addons: ['Highly Detailed', 'Masterpiece', 'Professional Photography'],
        },
    },
    {
        id: 'lifestyleCasual',
        category: 'common',
        icon: '☕',
        data: {
            background: 'Coffee Shop',
            lighting: ['Natural Window Light', 'Ambient Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Casual Wear', 'Jeans and T-shirt'],
            pose: ['Candid/Natural', 'Relaxed Sitting'],
            action: ['Drinking Coffee', 'Reading'],
            mood: ['Relaxed', 'Authentic', 'Cozy'],
            style: ['Lifestyle Photography', 'Candid Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Photorealistic', 'Natural Lighting'],
        },
    },
    {
        id: 'fitnessSports',
        category: 'common',
        icon: '💪',
        data: {
            background: 'Gym',
            lighting: ['Dramatic Lighting', 'Side Lighting'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Athletic Wear', 'Sports Outfit'],
            pose: ['Action Pose', 'Dynamic Movement'],
            action: ['Exercising', 'Athletic Pose'],
            mood: ['Energetic', 'Powerful', 'Determined'],
            style: ['Sports Photography', 'Action Photography'],
            colorGrading: 'High Contrast',
            addons: ['Sharp Focus', 'Highly Detailed', 'Motion Capture'],
        },
    },
    {
        id: 'businessCasual',
        category: 'common',
        icon: '👨‍💼',
        data: {
            background: 'Modern Office',
            lighting: ['Natural Window Light', 'Studio Lighting'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Smart Casual', 'Business Casual'],
            pose: ['Confident Stance', 'Front Facing Portrait'],
            mood: ['Professional', 'Approachable', 'Confident'],
            style: ['Corporate Photography', 'Lifestyle Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
        },
    },
    {
        id: 'outdoorAdventure',
        category: 'common',
        icon: '⛰️',
        data: {
            background: 'Mountain Landscape',
            timeOfDay: 'Afternoon',
            weather: ['Clear'],
            lighting: ['Natural Sunlight', 'Golden Hour Light'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Outdoor Gear', 'Hiking Outfit'],
            pose: ['Action Pose', 'Adventure Pose'],
            action: ['Hiking', 'Exploring'],
            mood: ['Adventurous', 'Free', 'Energetic'],
            style: ['Adventure Photography', 'Outdoor Photography'],
            colorGrading: 'Vibrant',
            addons: ['Highly Detailed', 'Photorealistic', 'Sharp Focus'],
        },
    },
    {
        id: 'petWithPerson',
        category: 'common',
        icon: '🐕',
        data: {
            background: 'Park',
            lighting: ['Soft Natural Light', 'Golden Hour Light'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            pose: ['With Pet', 'Candid/Natural'],
            action: ['Playing with Pet', 'Hugging Pet'],
            mood: ['Joyful', 'Playful', 'Loving'],
            style: ['Lifestyle Photography', 'Pet Photography'],
            colorGrading: 'Warm Tones',
            specialEffects: ['Bokeh'],
            addons: ['Highly Detailed', 'Photorealistic', 'Sharp Focus'],
        },
    },
    {
        id: 'maternityGlow',
        category: 'common',
        icon: '🤰',
        data: {
            background: 'Natural Outdoors',
            lighting: ['Soft Natural Light', 'Golden Hour Light', 'Backlight'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            pose: ['Maternity Pose', 'Side Profile'],
            clothing: ['Flowing Dress', 'Maternity Gown'],
            mood: ['Serene', 'Romantic', 'Dreamy', 'Joyful'],
            style: ['Maternity Photography', 'Portrait Photography'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Soft Glow', 'Bokeh'],
            addons: ['Highly Detailed', 'Professional Photography', 'Photorealistic'],
        },
    },
    {
        id: 'graduationDay',
        category: 'common',
        icon: '🎓',
        data: {
            background: 'University Campus',
            lighting: ['Natural Sunlight', 'Soft Natural Light'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Graduation Gown', 'Cap and Gown'],
            accessories: ['Graduation Cap', 'Diploma'],
            pose: ['Confident Stance', 'Front Facing Portrait', 'Celebrating'],
            action: ['Throwing Cap', 'Holding Diploma', 'Smiling'],
            mood: ['Proud', 'Confident', 'Joyful', 'Accomplished'],
            style: ['Portrait Photography', 'Event Photography'],
            colorGrading: 'Vibrant',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'familyPortrait',
        category: 'common',
        icon: '👨‍👩‍👧‍👦',
        data: {
            background: 'Park',
            lighting: ['Soft Natural Light', 'Golden Hour Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Coordinated Outfits', 'Casual Wear'],
            pose: ['Group Portrait', 'Candid/Natural'],
            action: ['Family Interaction', 'Laughing Together'],
            mood: ['Warm', 'Loving', 'Joyful', 'Authentic'],
            style: ['Family Photography', 'Portrait Photography'],
            colorGrading: 'Warm Tones',
            specialEffects: ['Bokeh'],
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'datingProfile',
        category: 'common',
        icon: '💝',
        data: {
            background: 'Urban City',
            lighting: ['Natural Window Light', 'Soft Natural Light'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Casual Wear', 'Smart Casual'],
            pose: ['Candid/Natural', 'Friendly Smile', 'Relaxed Sitting'],
            action: ['Natural Expression', 'Genuine Smile'],
            mood: ['Approachable', 'Friendly', 'Confident', 'Authentic'],
            style: ['Lifestyle Photography', 'Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Photorealistic', 'Natural Lighting'],
        },
    },
    {
        id: 'authorSpeaker',
        category: 'common',
        icon: '📚',
        data: {
            background: 'Library',
            lighting: ['Natural Window Light', 'Soft Natural Light'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Smart Casual', 'Business Casual', 'Blazer'],
            pose: ['Thoughtful Pose', 'With Books', 'Front Facing Portrait'],
            action: ['Reading', 'Thinking', 'Confident'],
            mood: ['Intellectual', 'Professional', 'Confident', 'Approachable'],
            style: ['Corporate Photography', 'Environmental Portrait'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
        },
    },
    {
        id: 'summerVibes',
        category: 'common',
        icon: '🌞',
        data: {
            background: 'Beach',
            timeOfDay: 'Afternoon',
            weather: ['Clear'],
            lighting: ['Natural Sunlight', 'Bright Daylight'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Summer Outfit', 'Beachwear', 'Sunglasses'],
            accessories: ['Sunglasses', 'Hat'],
            pose: ['Candid/Natural', 'Relaxed'],
            mood: ['Cheerful', 'Carefree', 'Energetic', 'Happy'],
            style: ['Lifestyle Photography', 'Beach Photography'],
            colorGrading: 'Vibrant',
            addons: ['Highly Detailed', 'Photorealistic', 'Sharp Focus'],
        },
    },
    {
        id: 'winterPortrait',
        category: 'common',
        icon: '❄️',
        data: {
            background: 'Winter Landscape',
            timeOfDay: 'Afternoon',
            weather: ['Snowy', 'Overcast'],
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Winter Coat', 'Scarf', 'Sweater'],
            accessories: ['Beanie', 'Scarf', 'Gloves'],
            pose: ['Candid/Natural', 'Front Facing Portrait'],
            mood: ['Cozy', 'Serene', 'Peaceful'],
            style: ['Portrait Photography', 'Seasonal Photography'],
            colorGrading: 'Cool Tones',
            specialEffects: ['Bokeh', 'Snow Effects'],
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'musicianPerformer',
        category: 'common',
        icon: '🎸',
        data: {
            background: 'Concert Stage',
            lighting: ['Stage Lighting', 'Colored Gels', 'Dramatic Lighting'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Stage Outfit', 'Rock Style'],
            accessories: ['Instrument', 'Microphone'],
            pose: ['Performance Pose', 'Action Pose'],
            action: ['Playing Instrument', 'Singing'],
            mood: ['Passionate', 'Energetic', 'Dynamic'],
            style: ['Concert Photography', 'Music Photography'],
            colorGrading: 'High Contrast',
            addons: ['Highly Detailed', 'Motion Capture', 'Professional Photography'],
        },
    },
    {
        id: 'chefCulinary',
        category: 'common',
        icon: '👨‍🍳',
        data: {
            background: 'Restaurant Kitchen',
            lighting: ['Natural Window Light', 'Warm Ambient Light'],
            lens: ['50mm Standard Lens', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Chef Uniform', 'Apron'],
            accessories: ['Chef Hat'],
            pose: ['Working Pose', 'Action Pose'],
            action: ['Cooking', 'Preparing Food'],
            mood: ['Professional', 'Focused', 'Passionate'],
            style: ['Culinary Photography', 'Commercial Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'yogaWellness',
        category: 'common',
        icon: '🧘',
        data: {
            background: 'Yoga Studio',
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Yoga Attire', 'Athletic Wear'],
            pose: ['Yoga Pose', 'Meditation Pose'],
            action: ['Stretching', 'Meditating'],
            mood: ['Peaceful', 'Serene', 'Focused'],
            style: ['Wellness Photography', 'Lifestyle Photography'],
            colorGrading: 'Soft Pastel',
            addons: ['Highly Detailed', 'Photorealistic', 'Natural Light'],
        },
    },
    {
        id: 'libraryScholar',
        category: 'common',
        icon: '📚',
        data: {
            background: 'Library',
            lighting: ['Natural Window Light', 'Ambient Light', 'Reading Light'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Smart Casual', 'Academic Attire'],
            accessories: ['Glasses', 'Books'],
            pose: ['Reading Pose', 'Studious Pose'],
            action: ['Reading', 'Studying'],
            mood: ['Intellectual', 'Focused', 'Peaceful'],
            style: ['Lifestyle Photography', 'Portrait Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'dancer',
        category: 'common',
        icon: '💃',
        data: {
            background: 'Dance Studio',
            lighting: ['Dramatic Lighting', 'Stage Lighting', 'Backlight'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Dance Outfit', 'Performance Attire'],
            pose: ['Dance Pose', 'Dynamic Movement'],
            action: ['Dancing', 'Performing'],
            mood: ['Graceful', 'Energetic', 'Passionate'],
            style: ['Dance Photography', 'Performance Photography'],
            colorGrading: 'Vibrant',
            specialEffects: ['Motion Blur'],
            addons: ['Highly Detailed', 'Motion Capture', 'Professional Photography'],
        },
    },
    {
        id: 'beachSunset',
        category: 'common',
        icon: '🏖️',
        data: {
            background: 'Beach',
            timeOfDay: 'Sunset',
            weather: ['Clear'],
            lighting: ['Golden Hour Light', 'Backlight', 'Natural Sunlight'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Beach Wear', 'Summer Dress'],
            pose: ['Silhouette', 'Walking Pose'],
            mood: ['Peaceful', 'Romantic', 'Free'],
            style: ['Beach Photography', 'Lifestyle Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'artistStudio',
        category: 'common',
        icon: '🎨',
        data: {
            background: 'Art Studio',
            lighting: ['Natural Window Light', 'Soft Diffused Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Casual Wear', 'Artist Smock'],
            accessories: ['Paint Brushes', 'Palette'],
            pose: ['Creative Pose', 'Working Pose'],
            action: ['Painting', 'Creating Art'],
            mood: ['Creative', 'Focused', 'Artistic'],
            style: ['Lifestyle Photography', 'Documentary Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'gardenBotanical',
        category: 'common',
        icon: '🌺',
        data: {
            background: 'Botanical Garden',
            timeOfDay: 'Morning',
            weather: ['Clear'],
            lighting: ['Soft Natural Light', 'Dappled Light'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Summer Dress', 'Floral Outfit'],
            pose: ['Garden Pose', 'Natural Pose'],
            action: ['Smelling Flowers', 'Walking'],
            mood: ['Peaceful', 'Fresh', 'Natural'],
            style: ['Nature Photography', 'Portrait Photography'],
            colorGrading: 'Vibrant',
            specialEffects: ['Bokeh'],
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },
    {
        id: 'rainyday',
        category: 'common',
        icon: '☔',
        data: {
            background: 'City Street',
            weather: ['Rain'],
            lighting: ['Overcast Light', 'Street Lights'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Raincoat', 'Rain Gear'],
            accessories: ['Umbrella'],
            pose: ['Walking Pose', 'Candid/Natural'],
            mood: ['Moody', 'Contemplative', 'Atmospheric'],
            style: ['Street Photography', 'Environmental Portrait'],
            colorGrading: 'Cool Tones',
            specialEffects: ['Rain Effects', 'Wet Reflections'],
            addons: ['Highly Detailed', 'Atmospheric', 'Professional Photography'],
        },
    },
    {
        id: 'motorcycleRider',
        category: 'common',
        icon: '🏍️',
        data: {
            background: 'Open Road',
            lighting: ['Natural Sunlight', 'Golden Hour Light'],
            lens: ['35mm Wide Angle', '24mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Leather Jacket', 'Biker Outfit'],
            accessories: ['Helmet', 'Sunglasses'],
            pose: ['Action Pose', 'Confident Stance'],
            action: ['Riding', 'Standing with Bike'],
            mood: ['Adventurous', 'Bold', 'Free'],
            style: ['Lifestyle Photography', 'Action Photography'],
            colorGrading: 'High Contrast',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'architecturalPortrait',
        category: 'common',
        icon: '🏛️',
        data: {
            background: 'Modern Architecture',
            lighting: ['Natural Sunlight', 'Architectural Lighting'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            composition: ['Leading Lines', 'Symmetrical Framing'],
            pose: ['Architectural Pose', 'Model Pose'],
            mood: ['Modern', 'Bold', 'Confident'],
            style: ['Architectural Photography', 'Fashion Photography'],
            colorGrading: 'High Contrast',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'cafeBarista',
        category: 'common',
        icon: '☕',
        data: {
            background: 'Artisan Cafe',
            lighting: ['Natural Window Light', 'Warm Ambient Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Apron', 'Casual Wear'],
            accessories: ['Coffee Cup'],
            pose: ['Working Pose', 'Barista Pose'],
            action: ['Making Coffee', 'Serving'],
            mood: ['Warm', 'Friendly', 'Cozy'],
            style: ['Lifestyle Photography', 'Commercial Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Photorealistic', 'Natural Lighting'],
        },
    },
    {
        id: 'forestNature',
        category: 'common',
        icon: '🌲',
        data: {
            background: 'Forest',
            timeOfDay: 'Afternoon',
            weather: ['Partly Cloudy'],
            lighting: ['Dappled Light', 'Natural Sunlight', 'Forest Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Outdoor Gear', 'Natural Colors'],
            pose: ['Natural Pose', 'Environmental Pose'],
            mood: ['Peaceful', 'Natural', 'Serene'],
            style: ['Nature Photography', 'Environmental Portrait'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Photorealistic', 'Professional Photography'],
        },
    },

    // ============ CREATIVE PRESETS (30) ============

    {
        id: 'cyberpunkNeon',
        category: 'creative',
        icon: '🌃',
        data: {
            background: 'Cyberpunk City',
            era: 'Cyberpunk Future',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Neon Lights', 'Colored Gels'],
            lightColor: 'Neon Pink/Blue',
            lens: ['35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Cyberpunk Outfit', 'Techwear'],
            accessories: ['Smart Glasses', 'Cybernetic Mask'],
            mood: ['Futuristic', 'Electric'],
            style: ['Cyberpunk', 'Sci-Fi Photography'],
            colorGrading: 'Neon Noir',
            specialEffects: ['Neon Glow', 'Chromatic Aberration', 'Rain Effects'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece'],
        },
    },
    {
        id: 'fantasyPortrait',
        category: 'creative',
        icon: '🧝',
        data: {
            background: 'Enchanted Forest',
            era: 'Fantasy Medieval',
            lighting: ['Ethereal Glow', 'Magical Lighting'],
            lightColor: 'Mystical Purple',
            lens: ['85mm Portrait Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            clothing: ['Fantasy Robes', 'Elven Attire'],
            accessories: ['Crown', 'Tiara'],
            eyeColor: 'Galaxy/Cosmic Eyes',
            mood: ['Mystical', 'Ethereal'],
            style: ['Fantasy Art', 'Digital Painting'],
            colorGrading: 'Fantasy Color Grade',
            specialEffects: ['Particle Effects', 'Magic Sparkles', 'Lens Flare'],
            addons: ['Highly Detailed', 'Masterpiece', '8K Resolution'],
        },
    },
    {
        id: 'vintageFilm',
        category: 'creative',
        icon: '📽️',
        data: {
            background: 'Retro Diner',
            era: '1970s',
            lighting: ['Available Light', 'Natural Sunlight'],
            lens: ['50mm Standard Lens'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            filmStock: ['Kodak Portra 400', 'Fujifilm Pro 400H'],
            clothing: ['Vintage 50s', 'Retro 60s'],
            mood: ['Nostalgic', 'Vintage'],
            style: ['Film Photography', 'Analog Photography'],
            colorGrading: 'Vintage Film',
            specialEffects: ['Film Grain', 'Light Leaks', 'Vignette'],
            texture: ['Film Grain'],
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'vaporwave',
        category: 'creative',
        icon: '🌴',
        data: {
            background: 'Neon Grid',
            era: '1980s',
            timeOfDay: 'Sunset',
            lighting: ['Neon Lights', 'Colored Gels'],
            lightColor: 'Neon Pink/Blue',
            lens: ['35mm Wide Angle'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            clothing: ['80s Neon Fashion', 'Streetwear'],
            accessories: ['Oversized Sunglasses'],
            mood: ['Retro', 'Dreamy'],
            style: ['Vaporwave', 'Retrowave'],
            colorGrading: 'Vaporwave',
            specialEffects: ['Chromatic Aberration', 'Glitch Effect', 'VHS Effect'],
            addons: ['Highly Detailed', 'Masterpiece'],
        },
    },
    {
        id: 'gothicDark',
        category: 'creative',
        icon: '🦇',
        data: {
            background: 'Gothic Cathedral',
            era: 'Victorian',
            timeOfDay: 'Night',
            weather: ['Foggy'],
            lighting: ['Low Key Lighting', 'Dramatic Shadows'],
            lightColor: 'Cool Blue',
            lens: ['50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Gothic Attire', 'Victorian'],
            makeup: ['Goth/Dark'],
            accessories: ['Choker', 'Rings'],
            mood: ['Dark', 'Mysterious', 'Moody'],
            style: ['Gothic Photography', 'Dark Art'],
            colorGrading: 'Dark Moody',
            specialEffects: ['Fog', 'Vignette'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'steampunkVictorian',
        category: 'creative',
        icon: '⚙️',
        data: {
            background: 'Industrial Victorian',
            era: 'Victorian',
            lighting: ['Dramatic Lighting', 'Gas Light'],
            lightColor: 'Warm Amber',
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            clothing: ['Steampunk Attire', 'Victorian'],
            accessories: ['Goggles', 'Pocket Watch', 'Gears'],
            mood: ['Vintage', 'Industrial', 'Dramatic'],
            style: ['Steampunk Art', 'Victorian Photography'],
            colorGrading: 'Sepia',
            specialEffects: ['Steam', 'Brass Tones', 'Vignette'],
            addons: ['Highly Detailed', 'Intricate Details', 'Masterpiece'],
        },
    },
    {
        id: 'animeManga',
        category: 'creative',
        icon: '🎌',
        data: {
            background: 'Anime Background',
            lighting: ['Soft Cel-Shaded Light', 'Anime Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Digital Art',
            eyeColor: 'Large Expressive Eyes',
            hairStyle: ['Anime Hair'],
            mood: ['Energetic', 'Expressive', 'Vibrant'],
            style: ['Anime Art', 'Manga Style', 'Japanese Animation'],
            colorGrading: 'Vibrant Anime',
            specialEffects: ['Cel Shading', 'Anime Effects'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece', 'Anime Style'],
        },
    },
    {
        id: 'popArt',
        category: 'creative',
        icon: '🎨',
        data: {
            background: 'Bold Color Blocks',
            era: '1960s',
            lighting: ['High Key Lighting', 'Flat Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            makeup: ['Bold/Statement', 'Bright Lipstick'],
            mood: ['Bold', 'Vibrant', 'Energetic'],
            style: ['Pop Art', 'Andy Warhol Style', 'Comic Book'],
            colorGrading: 'Bold Primary Colors',
            specialEffects: ['Halftone Dots', 'Ben-Day Dots', 'High Contrast'],
            addons: ['Highly Detailed', 'Graphic Style', 'Masterpiece'],
        },
    },
    {
        id: 'filmNoir',
        category: 'creative',
        icon: '🎭',
        data: {
            background: 'Dark Alley',
            era: '1940s',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Low Key Lighting', 'Dramatic Shadows', 'Venetian Blinds Shadow'],
            lightColor: 'Cool Blue',
            lens: ['50mm Standard Lens'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            filmStock: ['Ilford HP5', 'Kodak Tri-X'],
            clothing: ['Trench Coat', 'Fedora'],
            mood: ['Mysterious', 'Dramatic', 'Noir'],
            style: ['Film Noir', 'Black and White Photography'],
            colorGrading: 'Black and White',
            specialEffects: ['Film Grain', 'High Contrast', 'Rain Effects'],
            addons: ['Highly Detailed', 'Cinematic', 'Masterpiece'],
        },
    },
    {
        id: 'watercolorPainting',
        category: 'creative',
        icon: '🖌️',
        data: {
            background: 'Painted Background',
            lighting: ['Soft Diffused Light', 'Natural Light'],
            mood: ['Dreamy', 'Artistic', 'Soft'],
            style: ['Watercolor Painting', 'Fine Art', 'Painted Portrait'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Watercolor Texture', 'Painted Edges', 'Soft Blending'],
            texture: ['Watercolor Paper', 'Canvas'],
            addons: ['Highly Detailed', 'Artistic', 'Masterpiece', 'Hand Painted'],
        },
    },
    {
        id: 'neonPortrait',
        category: 'creative',
        icon: '💡',
        data: {
            background: 'Dark Studio',
            timeOfDay: 'Night',
            lighting: ['Neon Lights', 'Colored Gels', 'Dramatic Lighting'],
            lightColor: 'Neon Pink/Blue',
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Mirrorless',
            cameraType: 'Professional DSLR',
            pose: ['Front Facing Portrait', 'Fashion Pose'],
            mood: ['Bold', 'Edgy', 'Dramatic', 'Electric'],
            style: ['Neon Photography', 'Creative Portrait'],
            colorGrading: 'Neon Noir',
            specialEffects: ['Neon Glow', 'Colored Light', 'High Contrast'],
            addons: ['Highly Detailed', 'Sharp Focus', 'Masterpiece'],
        },
    },
    {
        id: 'horrorDark',
        category: 'creative',
        icon: '🎃',
        data: {
            background: 'Haunted House',
            timeOfDay: 'Night',
            weather: ['Foggy'],
            lighting: ['Low Key Lighting', 'Dramatic Shadows', 'Spooky Lighting'],
            lightColor: 'Cool Blue',
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            makeup: ['Goth/Dark', 'Dramatic'],
            mood: ['Dark', 'Eerie', 'Creepy', 'Haunting'],
            style: ['Horror Photography', 'Dark Art', 'Gothic Photography'],
            colorGrading: 'Dark Moody',
            specialEffects: ['Fog', 'Vignette', 'Grain'],
            addons: ['Highly Detailed', 'Cinematic', 'Atmospheric'],
        },
    },
    {
        id: 'sciFiFuture',
        category: 'creative',
        icon: '🚀',
        data: {
            background: 'Futuristic Space Station',
            era: 'Sci-Fi Future',
            lighting: ['Volumetric Lighting', 'Cinematic Lighting', 'Neon Lights'],
            lightColor: 'Cool Blue',
            lens: ['35mm Wide Angle'],
            camera: 'Cinema Camera',
            cameraType: 'Cinema Camera',
            clothing: ['Sci-Fi Suit', 'Space Suit', 'Futuristic Outfit'],
            accessories: ['Helmet', 'Tech Gear'],
            mood: ['Futuristic', 'Epic', 'Cinematic'],
            style: ['Sci-Fi Photography', 'Cinematic Photography', 'Futuristic Art'],
            colorGrading: 'Cinematic Color Grade',
            specialEffects: ['Lens Flare', 'Particle Effects', 'Holographic Effects'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'artDeco',
        category: 'creative',
        icon: '🏛️',
        data: {
            background: 'Art Deco Interior',
            era: '1920s',
            lighting: ['Dramatic Lighting', 'Glamour Lighting'],
            lightColor: 'Warm Golden',
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            clothing: ['1920s Fashion', 'Flapper Dress', 'Vintage 20s'],
            accessories: ['Pearl Necklace', 'Headband', 'Feather'],
            makeup: ['Glamorous/Full Glam', 'Vintage Makeup'],
            mood: ['Glamorous', 'Elegant', 'Vintage', 'Luxurious'],
            style: ['Art Deco Photography', 'Vintage Photography', 'Glamour Photography'],
            colorGrading: 'Sepia',
            specialEffects: ['Film Grain', 'Vignette', 'Gold Tones'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'surrealDream',
        category: 'creative',
        icon: '🌀',
        data: {
            background: 'Surreal Dreamscape',
            lighting: ['Ethereal Glow', 'Magical Lighting', 'Dramatic Lighting'],
            lightColor: 'Mystical Purple',
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Medium Format',
            mood: ['Surreal', 'Dreamlike', 'Mysterious', 'Otherworldly'],
            style: ['Surreal Art', 'Digital Art', 'Fantasy Art'],
            colorGrading: 'Fantasy Color Grade',
            specialEffects: ['Double Exposure', 'Particle Effects', 'Dream Effects', 'Distortion'],
            addons: ['Highly Detailed', 'Masterpiece', '8K Resolution', 'Artistic'],
        },
    },
    {
        id: 'impressionist',
        category: 'creative',
        icon: '🌻',
        data: {
            background: 'Garden',
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Medium Format',
            mood: ['Dreamy', 'Artistic', 'Peaceful', 'Romantic'],
            style: ['Impressionist Painting', 'Fine Art', 'Painted Portrait'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Painted Texture', 'Soft Focus', 'Brush Strokes'],
            texture: ['Canvas', 'Oil Paint'],
            addons: ['Highly Detailed', 'Artistic', 'Masterpiece', 'Impressionist Style'],
        },
    },
    {
        id: 'comicBook',
        category: 'creative',
        icon: '💥',
        data: {
            background: 'Bold Color Blocks',
            lighting: ['High Key Lighting', 'Dramatic Lighting'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Digital Art',
            pose: ['Action Pose', 'Dynamic Movement'],
            mood: ['Bold', 'Energetic', 'Dynamic', 'Powerful'],
            style: ['Comic Book Art', 'Graphic Novel', 'Pop Art'],
            colorGrading: 'Bold Primary Colors',
            specialEffects: ['Halftone Dots', 'Comic Outline', 'Action Lines', 'High Contrast'],
            addons: ['Highly Detailed', 'Graphic Style', 'Masterpiece', 'Bold Inking'],
        },
    },
    {
        id: 'oilPaintingClassic',
        category: 'creative',
        icon: '🖼️',
        data: {
            background: 'Renaissance Background',
            lighting: ['Rembrandt Lighting', 'Dramatic Lighting'],
            lightColor: 'Warm Golden',
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            era: 'Renaissance',
            clothing: ['Classical Attire', 'Period Costume'],
            mood: ['Dramatic', 'Classical', 'Elegant'],
            style: ['Oil Painting', 'Classical Art', 'Renaissance Portrait'],
            colorGrading: 'Oil Paint',
            specialEffects: ['Brush Strokes', 'Canvas Texture', 'Varnish Finish'],
            texture: ['Canvas', 'Oil Paint'],
            addons: ['Highly Detailed', 'Masterpiece', 'Museum Quality', 'Fine Art'],
        },
    },
    {
        id: 'holographicFuture',
        category: 'creative',
        icon: '✨',
        data: {
            background: 'Holographic Environment',
            lighting: ['Neon Lights', 'Holographic Glow', 'Colored Lights'],
            lightColor: 'Iridescent',
            lens: ['50mm Standard Lens'],
            camera: 'Digital Art',
            mood: ['Futuristic', 'Ethereal', 'Otherworldly'],
            style: ['Holographic Art', 'Digital Art', 'Futuristic Photography'],
            colorGrading: 'Holographic',
            specialEffects: ['Holographic Effect', 'Prismatic Light', 'Rainbow Reflection', 'Glitch'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece', 'Iridescent'],
        },
    },
    {
        id: 'minimalistMonochrome',
        category: 'creative',
        icon: '⬜',
        data: {
            background: 'Minimal White',
            lighting: ['Soft Diffused Light', 'Minimal Shadows'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Medium Format',
            composition: ['Minimalist', 'Negative Space'],
            mood: ['Calm', 'Pure', 'Minimal'],
            style: ['Minimalist Photography', 'Fine Art'],
            colorGrading: 'Black and White',
            addons: ['Highly Detailed', 'Clean', 'Professional Photography', 'Minimalist'],
        },
    },
    {
        id: 'doubleExposure',
        category: 'creative',
        icon: '🌃',
        data: {
            background: 'Multiple Exposures',
            lighting: ['Natural Light', 'Cinematic Lighting'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Film Camera',
            filmStock: ['Kodak Portra 400'],
            mood: ['Artistic', 'Dreamy', 'Surreal'],
            style: ['Double Exposure', 'Fine Art Photography', 'Creative Photography'],
            specialEffects: ['Double Exposure', 'Multiple Exposure', 'Overlay'],
            addons: ['Highly Detailed', 'Artistic', 'Masterpiece', 'Creative'],
        },
    },
    {
        id: 'neonCyberpunk',
        category: 'creative',
        icon: '🌆',
        data: {
            background: 'Neon City',
            era: 'Cyberpunk Future',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Neon Lights', 'Dramatic Lighting', 'Colored Gels'],
            lightColor: 'Neon Pink/Blue',
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            clothing: ['Cyberpunk Fashion', 'Futuristic Streetwear'],
            accessories: ['Cybernetic Implants', 'Tech Accessories'],
            mood: ['Edgy', 'Futuristic', 'Noir'],
            style: ['Cyberpunk Photography', 'Neon Noir', 'Sci-Fi Photography'],
            colorGrading: 'Neon Noir',
            specialEffects: ['Neon Glow', 'Rain Effects', 'Wet Streets', 'Neon Reflections'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'abstractExpressionism',
        category: 'creative',
        icon: '🎨',
        data: {
            background: 'Abstract Background',
            lighting: ['Dramatic Lighting', 'Colored Lights'],
            mood: ['Bold', 'Emotional', 'Abstract', 'Artistic'],
            style: ['Abstract Art', 'Expressionism', 'Contemporary Art'],
            colorGrading: 'Bold Saturated',
            specialEffects: ['Paint Splatter', 'Abstract Shapes', 'Color Wash', 'Distortion'],
            texture: ['Canvas', 'Acrylic Paint'],
            addons: ['Highly Detailed', 'Artistic', 'Masterpiece', 'Museum Quality'],
        },
    },
    {
        id: 'desertSunset',
        category: 'creative',
        icon: '🏜️',
        data: {
            background: 'Desert',
            timeOfDay: 'Sunset',
            weather: ['Clear'],
            lighting: ['Golden Hour Light', 'Dramatic Lighting', 'Backlighting'],
            lightColor: 'Warm Orange',
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            clothing: ['Flowing Dress', 'Desert Fashion'],
            mood: ['Dramatic', 'Mystical', 'Epic'],
            style: ['Landscape Portrait', 'Adventure Photography'],
            colorGrading: 'Warm Dramatic',
            specialEffects: ['Lens Flare', 'Dust Particles'],
            addons: ['Highly Detailed', 'Cinematic', 'Masterpiece', 'Epic'],
        },
    },
    {
        id: 'retroFuturism',
        category: 'creative',
        icon: '🚀',
        data: {
            background: 'Retro-Futuristic',
            era: '1950s Future Vision',
            lighting: ['Volumetric Lighting', 'Dramatic Lighting'],
            lightColor: 'Retro Orange',
            lens: ['35mm Wide Angle'],
            camera: 'Cinema Camera',
            clothing: ['Retro Sci-Fi Outfit', 'Space Age Fashion'],
            mood: ['Nostalgic', 'Futuristic', 'Optimistic'],
            style: ['Retrofuturism', 'Vintage Sci-Fi', 'Atomic Age'],
            colorGrading: 'Vintage Sci-Fi',
            specialEffects: ['Vintage Film Look', 'Ray Gun Effects'],
            addons: ['Highly Detailed', 'Masterpiece', 'Retro-Futuristic', 'Cinematic'],
        },
    },
    {
        id: 'underwaterDream',
        category: 'creative',
        icon: '🌊',
        data: {
            background: 'Underwater',
            lighting: ['Underwater Light', 'Volumetric Light Rays', 'Blue Light'],
            lightColor: 'Aqua Blue',
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Underwater Camera',
            clothing: ['Flowing Dress', 'Ethereal Fabric'],
            mood: ['Dreamy', 'Ethereal', 'Surreal', 'Peaceful'],
            style: ['Underwater Photography', 'Fine Art', 'Surreal Photography'],
            colorGrading: 'Underwater Blue',
            specialEffects: ['Underwater Effects', 'Bubbles', 'Light Rays', 'Floating Fabric'],
            addons: ['Highly Detailed', 'Masterpiece', '8K Resolution', 'Ethereal'],
        },
    },
    {
        id: 'japaneseAnime',
        category: 'creative',
        icon: '🎌',
        data: {
            background: 'Anime Background',
            lighting: ['Anime Lighting', 'Dramatic Shadows'],
            lens: ['50mm Standard Lens'],
            camera: 'Digital Art',
            clothing: ['Anime Fashion', 'Japanese Style'],
            mood: ['Dynamic', 'Expressive', 'Vibrant'],
            style: ['Anime', 'Japanese Animation', 'Manga Style'],
            colorGrading: 'Anime Colors',
            specialEffects: ['Anime Eyes', 'Sparkles', 'Speed Lines', 'Anime Shading'],
            addons: ['Highly Detailed', 'High Quality', 'Masterpiece', 'Anime Style'],
        },
    },
    {
        id: 'baroqueOpulence',
        category: 'creative',
        icon: '👑',
        data: {
            background: 'Baroque Palace',
            era: 'Baroque Period',
            lighting: ['Chandelier Light', 'Dramatic Lighting', 'Golden Light'],
            lightColor: 'Warm Golden',
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            clothing: ['Baroque Gown', 'Royal Attire', 'Period Costume'],
            accessories: ['Crown', 'Jewelry', 'Royal Accessories'],
            makeup: ['Glamorous/Full Glam', 'Historical Makeup'],
            mood: ['Opulent', 'Regal', 'Dramatic', 'Luxurious'],
            style: ['Baroque Art', 'Historical Portrait', 'Fine Art'],
            colorGrading: 'Rich Golden',
            texture: ['Silk', 'Velvet'],
            addons: ['Highly Detailed', 'Masterpiece', 'Museum Quality', 'Ornate'],
        },
    },
    {
        id: 'psychedelicTrip',
        category: 'creative',
        icon: '🌈',
        data: {
            background: 'Psychedelic Background',
            lighting: ['Colored Lights', 'Dramatic Lighting', 'Kaleidoscope'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Digital Art',
            mood: ['Surreal', 'Vibrant', 'Trippy', 'Mind-Bending'],
            style: ['Psychedelic Art', '60s Art', 'Acid Art'],
            colorGrading: 'Psychedelic',
            specialEffects: ['Kaleidoscope', 'Fractal Patterns', 'Color Distortion', 'Warping'],
            addons: ['Highly Detailed', 'Vibrant', 'Masterpiece', 'Psychedelic'],
        },
    },
    {
        id: 'noirDetective',
        category: 'creative',
        icon: '🕵️',
        data: {
            background: 'Detective Office',
            era: '1940s',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Low Key Lighting', 'Venetian Blinds Shadow', 'Single Light Source'],
            lightColor: 'Harsh White',
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Film Camera',
            filmStock: ['Ilford HP5'],
            clothing: ['Trench Coat', 'Fedora', 'Suit'],
            accessories: ['Cigarette', 'Magnifying Glass'],
            mood: ['Mysterious', 'Dark', 'Noir', 'Gritty'],
            style: ['Film Noir', 'Detective Noir', 'Classic Noir'],
            colorGrading: 'Black and White',
            specialEffects: ['Film Grain', 'High Contrast', 'Shadows', 'Rain'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic', 'Noir Atmosphere'],
        },
    },

    // ============ UTILITY PRESETS (35) ============

    {
        id: 'qualityEnhance',
        category: 'utility',
        icon: '✨',
        data: {
            addons: ['Highly Detailed', '8K Resolution', 'Sharp Focus', 'Masterpiece', 'Professional Photography', 'Photorealistic'],
            style: ['Ultra Realistic'],
        },
    },
    {
        id: 'lightRetouch',
        category: 'utility',
        icon: '🪄',
        data: {
            makeup: ['Natural/No-Makeup Makeup', 'Dewy/Glass Skin'],
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Photorealistic', 'Highly Detailed'],
        },
    },
    {
        id: 'skinPerfect',
        category: 'utility',
        icon: '💎',
        data: {
            makeup: ['Dewy/Glass Skin', 'Natural/No-Makeup Makeup', 'Heavy Highlighter/Strobing'],
            lighting: ['Beauty Dish', 'Softbox Lighting'],
            style: ['Beauty Photography'],
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'hdrVivid',
        category: 'utility',
        icon: '🌈',
        data: {
            colorGrading: 'HDR',
            lighting: ['High Dynamic Range'],
            addons: ['Highly Detailed', '8K Resolution', 'HDR'],
            style: ['HDR Photography'],
        },
    },
    {
        id: 'instagramReady',
        category: 'utility',
        icon: '📱',
        data: {
            aspectRatio: '1:1 Square',
            colorGrading: 'Vibrant',
            lighting: ['Soft Natural Light'],
            addons: ['Sharp Focus', 'Highly Detailed', 'Professional Photography'],
            style: ['Lifestyle Photography'],
        },
    },
    {
        id: 'linkedinPro',
        category: 'utility',
        icon: '👔',
        data: {
            background: 'Neutral Gray',
            pose: ['Headshot', 'Front Facing Portrait'],
            lighting: ['Studio Lighting', 'Softbox Lighting'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
            style: ['Corporate Photography'],
        },
    },
    {
        id: 'softDreamy',
        category: 'utility',
        icon: '☁️',
        data: {
            lighting: ['Soft Natural Light', 'Backlight'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Soft Glow', 'Bokeh'],
            mood: ['Dreamy', 'Romantic'],
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'sharpDetail',
        category: 'utility',
        icon: '🔍',
        data: {
            lens: ['Macro Lens'],
            composition: ['Close-up', 'Center Composition'],
            addons: ['Sharp Focus', 'Highly Detailed', '8K Resolution', 'Intricate Details'],
            style: ['Macro Photography'],
        },
    },
    {
        id: 'instantPro',
        category: 'utility',
        icon: '📸',
        data: {
            lens: ['85mm Portrait Lens'],
            camera: 'Mirrorless',
            cameraType: 'Professional DSLR',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            addons: ['Professional Photography', 'Highly Detailed', 'Masterpiece', '8K Resolution', 'Sharp Focus'],
            style: ['Professional Photography'],
        },
    },
    {
        id: 'hairPerfect',
        category: 'utility',
        icon: '💇‍♀️',
        data: {
            addons: ['Voluminous Hair', 'Detailed Hair Texture', 'Perfectly Styled Hair', 'Shiny Hair', 'High Quality'],
            lighting: ['Rim Lighting', 'Backlight'],
        },
    },
    {
        id: 'lightingFix',
        category: 'utility',
        icon: '💡',
        data: {
            lighting: ['Soft Natural Light', 'Diffused Lighting', 'Cinematic Lighting'],
            addons: ['Perfect Exposure', 'Balanced Lighting', 'Professional Lighting'],
        },
    },
    {
        id: 'outfitDetail',
        category: 'utility',
        icon: '👗',
        data: {
            addons: ['Detailed Fabric Texture', 'Intricate Patterns', 'High Quality Materials', 'Sharp Focus'],
            lighting: ['Studio Lighting'],
            cameraType: 'Professional DSLR',
        },
    },
    {
        id: 'backgroundBlur',
        category: 'utility',
        icon: '🌫️',
        data: {
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            composition: ['Shallow Depth of Field', 'Center Composition'],
            specialEffects: ['Bokeh', 'Creamy Bokeh'],
            addons: ['Sharp Subject Focus', 'Soft Background', 'Professional Bokeh'],
            style: ['Portrait Photography'],
        },
    },
    {
        id: 'colorPop',
        category: 'utility',
        icon: '🔴',
        data: {
            colorGrading: 'Selective Color',
            specialEffects: ['Selective Color Highlight'],
            addons: ['Highly Detailed', 'Vibrant Accent Color', 'Black and White Background'],
            style: ['Creative Photography'],
        },
    },
    {
        id: 'eyeEnhance',
        category: 'utility',
        icon: '👁️',
        data: {
            eyeColor: 'Vibrant Eye Color',
            lighting: ['Catchlight', 'Beauty Dish'],
            addons: ['Sparkling Eyes', 'Detailed Iris', 'Sharp Eye Focus', 'Enhanced Eye Color'],
            style: ['Beauty Photography'],
        },
    },
    {
        id: 'symmetryFix',
        category: 'utility',
        icon: '⚖️',
        data: {
            composition: ['Center Composition', 'Symmetrical Framing'],
            pose: ['Front Facing Portrait', 'Straight Angle'],
            addons: ['Perfect Symmetry', 'Balanced Features', 'Professional Photography'],
            lighting: ['Even Lighting', 'Softbox Lighting'],
        },
    },
    {
        id: 'zoomReady',
        category: 'utility',
        icon: '💻',
        data: {
            background: 'Neutral Gray',
            lighting: ['Studio Lighting', 'Softbox Lighting', 'Even Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            pose: ['Headshot', 'Front Facing Portrait', 'Eye Level'],
            composition: ['Center Composition', 'Headroom'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed', 'Good Lighting'],
            style: ['Corporate Photography'],
        },
    },
    {
        id: 'twitterProfile',
        category: 'utility',
        icon: '🐦',
        data: {
            aspectRatio: '1:1 Square',
            background: 'Simple Gradient',
            lighting: ['Soft Natural Light', 'Studio Lighting'],
            lens: ['85mm Portrait Lens'],
            pose: ['Headshot', 'Front Facing Portrait'],
            composition: ['Center Composition', 'Close-up'],
            colorGrading: 'Vibrant',
            addons: ['Sharp Focus', 'Highly Detailed', 'Professional Photography'],
            style: ['Portrait Photography'],
        },
    },
    {
        id: 'contrastBoost',
        category: 'utility',
        icon: '⚡',
        data: {
            lighting: ['Dramatic Lighting', 'Side Lighting'],
            colorGrading: 'High Contrast',
            specialEffects: ['High Contrast', 'Enhanced Shadows'],
            addons: ['Highly Detailed', 'Punchy Colors', 'Deep Blacks'],
            style: ['High Contrast Photography'],
        },
    },
    {
        id: 'vintageTone',
        category: 'utility',
        icon: '📼',
        data: {
            colorGrading: 'Vintage Film',
            filmStock: ['Kodak Portra 400', 'Fujifilm Pro 400H'],
            specialEffects: ['Film Grain', 'Light Leaks', 'Vignette', 'Faded Colors'],
            texture: ['Film Grain'],
            addons: ['Vintage Look', 'Nostalgic', 'Film Photography'],
            style: ['Film Photography', 'Analog Photography'],
        },
    },
    {
        id: 'professionalHeadroom',
        category: 'utility',
        icon: '📐',
        data: {
            composition: ['Rule of Thirds', 'Headroom', 'Eye Level'],
            pose: ['Front Facing Portrait', 'Professional Stance'],
            addons: ['Perfect Framing', 'Professional Composition', 'Balanced'],
            style: ['Professional Photography'],
        },
    },
    {
        id: 'goldenRatioComposition',
        category: 'utility',
        icon: '🔶',
        data: {
            composition: ['Golden Ratio', 'Fibonacci Spiral', 'Rule of Thirds'],
            addons: ['Perfect Composition', 'Mathematically Balanced', 'Professional Photography'],
            style: ['Fine Art Photography'],
        },
    },
    {
        id: 'dramaticShadows',
        category: 'utility',
        icon: '🌑',
        data: {
            lighting: ['Low Key Lighting', 'Side Lighting', 'Dramatic Shadows'],
            colorGrading: 'High Contrast',
            specialEffects: ['Enhanced Shadows', 'Deep Blacks'],
            addons: ['Highly Detailed', 'Dramatic', 'Moody'],
            style: ['Dramatic Photography'],
        },
    },
    {
        id: 'softGlam',
        category: 'utility',
        icon: '💫',
        data: {
            makeup: ['Glamorous/Full Glam', 'Heavy Highlighter/Strobing'],
            lighting: ['Beauty Dish', 'Softbox Lighting', 'Rim Lighting'],
            specialEffects: ['Soft Glow', 'Luminous Skin'],
            addons: ['Highly Detailed', 'Glamorous', 'Professional Photography'],
            style: ['Beauty Photography', 'Glamour Photography'],
        },
    },
    {
        id: 'motionFreeze',
        category: 'utility',
        icon: '❄️',
        data: {
            camera: 'High Speed Camera',
            cameraType: 'Professional DSLR',
            addons: ['Frozen Motion', 'Ultra Sharp', 'High Shutter Speed', 'Action Capture'],
            style: ['Action Photography', 'Sports Photography'],
        },
    },
    {
        id: 'wideAngleDramatic',
        category: 'utility',
        icon: '📐',
        data: {
            lens: ['24mm Wide Angle', '14mm Ultra Wide'],
            composition: ['Wide Angle Perspective', 'Dynamic Angles'],
            addons: ['Dramatic Perspective', 'Wide Coverage', 'Sharp Focus'],
            style: ['Wide Angle Photography'],
        },
    },
    {
        id: 'macroCloseup',
        category: 'utility',
        icon: '🔬',
        data: {
            lens: ['Macro Lens', '100mm Macro'],
            composition: ['Extreme Close-up', 'Center Composition'],
            lighting: ['Macro Ring Light', 'Diffused Lighting'],
            addons: ['Extreme Detail', 'Intricate Textures', 'Sharp Focus', '8K Resolution'],
            style: ['Macro Photography'],
        },
    },
    {
        id: 'warmGoldenTone',
        category: 'utility',
        icon: '🌟',
        data: {
            colorGrading: 'Warm Tones',
            lightColor: 'Warm Golden',
            lighting: ['Golden Hour Light', 'Warm Light'],
            addons: ['Warm Atmosphere', 'Cozy Feel', 'Golden Glow'],
            style: ['Golden Hour Photography'],
        },
    },
    {
        id: 'coolCinematic',
        category: 'utility',
        icon: '🎬',
        data: {
            colorGrading: 'Cinematic Color Grade',
            lightColor: 'Cool Blue',
            lighting: ['Cinematic Lighting', 'Dramatic Lighting'],
            addons: ['Cinematic Look', 'Film Grade', 'Professional Color'],
            style: ['Cinematic Photography'],
        },
    },
    {
        id: 'fashionEditorial',
        category: 'utility',
        icon: '📰',
        data: {
            lighting: ['High Key Lighting', 'Studio Lighting'],
            composition: ['Dynamic Angles', 'Fashion Composition'],
            pose: ['Fashion Pose', 'Editorial Pose'],
            addons: ['Magazine Quality', 'Editorial Style', 'High Fashion'],
            style: ['Editorial Photography', 'Fashion Photography'],
        },
    },
    {
        id: 'softFocusDreamy',
        category: 'utility',
        icon: '💭',
        data: {
            specialEffects: ['Soft Focus', 'Dreamy Filter', 'Diffusion'],
            lighting: ['Soft Diffused Light', 'Backlight'],
            colorGrading: 'Soft Pastel',
            addons: ['Dreamy Atmosphere', 'Romantic', 'Ethereal'],
            style: ['Fine Art Photography'],
        },
    },
    {
        id: 'urbanGritty',
        category: 'utility',
        icon: '🏙️',
        data: {
            background: 'Urban Environment',
            colorGrading: 'Desaturated',
            specialEffects: ['Film Grain', 'Gritty Texture'],
            mood: ['Gritty', 'Urban', 'Raw'],
            addons: ['Street Style', 'Authentic', 'Documentary Feel'],
            style: ['Street Photography', 'Urban Photography'],
        },
    },
    {
        id: 'professionalLinkedin',
        category: 'utility',
        icon: '💼',
        data: {
            background: 'Professional Background',
            lighting: ['Even Lighting', 'Softbox Lighting', 'Studio Lighting'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            pose: ['Professional Headshot', 'Front Facing Portrait'],
            composition: ['Headshot Framing', 'Eye Level'],
            colorGrading: 'Natural',
            addons: ['Professional Quality', 'Corporate Standard', 'Sharp Focus'],
            style: ['Corporate Photography', 'Professional Headshot'],
        },
    },
    {
        id: 'blackBackdrop',
        category: 'utility',
        icon: '⬛',
        data: {
            background: 'Solid Black',
            lighting: ['Dramatic Lighting', 'Side Lighting', 'Single Light Source'],
            composition: ['Center Composition', 'Isolated Subject'],
            colorGrading: 'High Contrast',
            addons: ['Dramatic', 'Bold', 'Isolated Subject', 'Dark Background'],
            style: ['Studio Photography', 'Dramatic Portrait'],
        },
    },
    {
        id: 'pastelsoftMood',
        category: 'utility',
        icon: '🎀',
        data: {
            colorGrading: 'Soft Pastel',
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            specialEffects: ['Soft Glow', 'Dreamy Filter'],
            mood: ['Soft', 'Gentle', 'Peaceful'],
            addons: ['Pastel Colors', 'Soft Aesthetic', 'Gentle Mood'],
            style: ['Soft Photography', 'Fine Art'],
        },
    },
];

// Helper to get presets by category
export const getPresetsByCategory = (category: 'common' | 'creative' | 'utility'): Preset[] => {
    return presets.filter((p) => p.category === category);
};

// Helper to get a preset by ID
export const getPresetById = (id: string): Preset | undefined => {
    return presets.find((p) => p.id === id);
};
