import { PromptData } from './prompt-builder';

export interface Preset {
    id: string;
    category: 'common' | 'creative' | 'utility';
    icon: string;
    data: Partial<PromptData>;
}

export const presets: Preset[] = [
    // ============ COMMON PRESETS (15) ============

    {
        id: 'studioPortrait',
        category: 'common',
        icon: '📸',
        data: {
            background: 'Simple Gradient',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Rule of Thirds', 'Center Composition'],
            pose: ['Front Facing Portrait', 'Headshot'],
            mood: ['Professional'],
            style: ['Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'editorialFashion',
        category: 'common',
        icon: '👗',
        data: {
            background: 'Fashion Studio',
            lighting: ['Dramatic Lighting', 'High Key Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Dynamic Angles', 'Leading Lines'],
            pose: ['Fashion Pose', 'Editorial Pose'],
            makeup: ['Editorial/High Fashion', 'Glamorous/Full Glam'],
            mood: ['Dramatic', 'Confident'],
            style: ['Fashion Photography', 'Editorial Photography'],
            colorGrading: 'High Contrast',
            addons: ['Highly Detailed', 'Masterpiece', 'Professional Photography'],
        },
    },
    {
        id: 'goldenHour',
        category: 'common',
        icon: '🌅',
        data: {
            background: 'Beach',
            timeOfDay: 'Golden Hour',
            weather: ['Clear'],
            lighting: ['Golden Hour Light', 'Natural Sunlight'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            lightColor: 'Warm Golden',
            mood: ['Romantic', 'Dreamy'],
            style: ['Portrait Photography'],
            colorGrading: 'Warm Tones',
            addons: ['Highly Detailed', 'Professional Photography', 'Photorealistic'],
        },
    },
    {
        id: 'productShot',
        category: 'common',
        icon: '📦',
        data: {
            background: 'Pure White',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            lens: ['Macro Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Center Composition', 'Minimalist'],
            mood: ['Clean', 'Professional'],
            style: ['Product Photography', 'Commercial Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Highly Detailed', '8K Resolution'],
        },
    },
    {
        id: 'streetPhotography',
        category: 'common',
        icon: '🏙️',
        data: {
            background: 'Urban City',
            timeOfDay: 'Afternoon',
            lighting: ['Natural Sunlight', 'Available Light'],
            lens: ['35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            composition: ['Leading Lines', 'Rule of Thirds'],
            pose: ['Candid/Natural', 'Walking Pose'],
            mood: ['Authentic', 'Urban'],
            style: ['Street Photography', 'Documentary Photography'],
            colorGrading: 'Urban Grit',
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'blackAndWhite',
        category: 'common',
        icon: '⚫',
        data: {
            background: 'Simple Gradient',
            lighting: ['Dramatic Lighting', 'Rembrandt Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            composition: ['Rule of Thirds', 'Dramatic Framing'],
            mood: ['Dramatic', 'Timeless'],
            style: ['Black and White Photography', 'Fine Art Photography'],
            colorGrading: 'Black and White',
            filmStock: ['Ilford HP5', 'Kodak Tri-X'],
            addons: ['Highly Detailed', 'Sharp Focus', 'Masterpiece'],
        },
    },
    {
        id: 'cinematic',
        category: 'common',
        icon: '🎬',
        data: {
            background: 'Moody Interior',
            lighting: ['Cinematic Lighting', 'Volumetric Lighting'],
            lens: ['Anamorphic Lens'],
            camera: 'Cinema Camera',
            cameraType: 'Cinema Camera',
            composition: ['Widescreen Framing', 'Rule of Thirds'],
            aspectRatio: '21:9 Cinematic',
            mood: ['Cinematic', 'Dramatic'],
            style: ['Cinematic Photography', 'Film Still'],
            colorGrading: 'Cinematic Color Grade',
            specialEffects: ['Lens Flare', 'Film Grain'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'naturalBeauty',
        category: 'common',
        icon: '🌿',
        data: {
            background: 'Natural Outdoors',
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            makeup: ['Natural/No-Makeup Makeup', 'Dewy/Glass Skin'],
            pose: ['Front Facing Portrait', 'Candid/Natural'],
            mood: ['Fresh', 'Natural'],
            style: ['Beauty Photography', 'Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Sharp Focus', 'Photorealistic'],
        },
    },
    {
        id: 'corporateHeadshot',
        category: 'common',
        icon: '💼',
        data: {
            background: 'Neutral Gray',
            lighting: ['Studio Lighting', 'Softbox Lighting'],
            lens: ['85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Business Suit', 'Blazer'],
            pose: ['Headshot', 'Front Facing Portrait'],
            action: ['Confident', 'Smiling'],
            mood: ['Professional', 'Confident'],
            style: ['Corporate Photography', 'Portrait Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
        },
    },
    {
        id: 'weddingBridal',
        category: 'common',
        icon: '💒',
        data: {
            background: 'Garden',
            lighting: ['Soft Natural Light', 'Backlight'],
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Wedding Dress'],
            mood: ['Romantic', 'Elegant', 'Dreamy'],
            style: ['Wedding Photography', 'Portrait Photography'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Bokeh', 'Soft Glow'],
            addons: ['Highly Detailed', 'Masterpiece', 'Professional Photography'],
        },
    },
    {
        id: 'lifestyleCasual',
        category: 'common',
        icon: '☕',
        data: {
            background: 'Coffee Shop',
            lighting: ['Natural Window Light', 'Ambient Light'],
            lens: ['35mm Wide Angle', '50mm Standard Lens'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Casual Wear', 'Jeans and T-shirt'],
            pose: ['Candid/Natural', 'Relaxed Sitting'],
            action: ['Drinking Coffee', 'Reading'],
            mood: ['Relaxed', 'Authentic', 'Cozy'],
            style: ['Lifestyle Photography', 'Candid Photography'],
            colorGrading: 'Natural',
            addons: ['Highly Detailed', 'Photorealistic', 'Natural Lighting'],
        },
    },
    {
        id: 'fitnessSports',
        category: 'common',
        icon: '💪',
        data: {
            background: 'Gym',
            lighting: ['Dramatic Lighting', 'Side Lighting'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Athletic Wear', 'Sports Outfit'],
            pose: ['Action Pose', 'Dynamic Movement'],
            action: ['Exercising', 'Athletic Pose'],
            mood: ['Energetic', 'Powerful', 'Determined'],
            style: ['Sports Photography', 'Action Photography'],
            colorGrading: 'High Contrast',
            addons: ['Sharp Focus', 'Highly Detailed', 'Motion Capture'],
        },
    },
    {
        id: 'businessCasual',
        category: 'common',
        icon: '👨‍💼',
        data: {
            background: 'Modern Office',
            lighting: ['Natural Window Light', 'Studio Lighting'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Smart Casual', 'Business Casual'],
            pose: ['Confident Stance', 'Front Facing Portrait'],
            mood: ['Professional', 'Approachable', 'Confident'],
            style: ['Corporate Photography', 'Lifestyle Photography'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
        },
    },
    {
        id: 'outdoorAdventure',
        category: 'common',
        icon: '⛰️',
        data: {
            background: 'Mountain Landscape',
            timeOfDay: 'Afternoon',
            weather: ['Clear'],
            lighting: ['Natural Sunlight', 'Golden Hour Light'],
            lens: ['24mm Wide Angle', '35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Outdoor Gear', 'Hiking Outfit'],
            pose: ['Action Pose', 'Adventure Pose'],
            action: ['Hiking', 'Exploring'],
            mood: ['Adventurous', 'Free', 'Energetic'],
            style: ['Adventure Photography', 'Outdoor Photography'],
            colorGrading: 'Vibrant',
            addons: ['Highly Detailed', 'Photorealistic', 'Sharp Focus'],
        },
    },
    {
        id: 'petWithPerson',
        category: 'common',
        icon: '🐕',
        data: {
            background: 'Park',
            lighting: ['Soft Natural Light', 'Golden Hour Light'],
            lens: ['50mm Standard Lens', '85mm Portrait Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            pose: ['With Pet', 'Candid/Natural'],
            action: ['Playing with Pet', 'Hugging Pet'],
            mood: ['Joyful', 'Playful', 'Loving'],
            style: ['Lifestyle Photography', 'Pet Photography'],
            colorGrading: 'Warm Tones',
            specialEffects: ['Bokeh'],
            addons: ['Highly Detailed', 'Photorealistic', 'Sharp Focus'],
        },
    },

    // ============ CREATIVE PRESETS (10) ============

    {
        id: 'cyberpunkNeon',
        category: 'creative',
        icon: '🌃',
        data: {
            background: 'Cyberpunk City',
            era: 'Cyberpunk Future',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Neon Lights', 'Colored Gels'],
            lightColor: 'Neon Pink/Blue',
            lens: ['35mm Wide Angle'],
            camera: 'Mirrorless',
            cameraType: 'Mirrorless Camera',
            clothing: ['Cyberpunk Outfit', 'Techwear'],
            accessories: ['Smart Glasses', 'Cybernetic Mask'],
            mood: ['Futuristic', 'Electric'],
            style: ['Cyberpunk', 'Sci-Fi Photography'],
            colorGrading: 'Neon Noir',
            specialEffects: ['Neon Glow', 'Chromatic Aberration', 'Rain Effects'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece'],
        },
    },
    {
        id: 'fantasyPortrait',
        category: 'creative',
        icon: '🧝',
        data: {
            background: 'Enchanted Forest',
            era: 'Fantasy Medieval',
            lighting: ['Ethereal Glow', 'Magical Lighting'],
            lightColor: 'Mystical Purple',
            lens: ['85mm Portrait Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            clothing: ['Fantasy Robes', 'Elven Attire'],
            accessories: ['Crown', 'Tiara'],
            eyeColor: 'Galaxy/Cosmic Eyes',
            mood: ['Mystical', 'Ethereal'],
            style: ['Fantasy Art', 'Digital Painting'],
            colorGrading: 'Fantasy Color Grade',
            specialEffects: ['Particle Effects', 'Magic Sparkles', 'Lens Flare'],
            addons: ['Highly Detailed', 'Masterpiece', '8K Resolution'],
        },
    },
    {
        id: 'vintageFilm',
        category: 'creative',
        icon: '📽️',
        data: {
            background: 'Retro Diner',
            era: '1970s',
            lighting: ['Available Light', 'Natural Sunlight'],
            lens: ['50mm Standard Lens'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            filmStock: ['Kodak Portra 400', 'Fujifilm Pro 400H'],
            clothing: ['Vintage 50s', 'Retro 60s'],
            mood: ['Nostalgic', 'Vintage'],
            style: ['Film Photography', 'Analog Photography'],
            colorGrading: 'Vintage Film',
            specialEffects: ['Film Grain', 'Light Leaks', 'Vignette'],
            texture: ['Film Grain'],
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'vaporwave',
        category: 'creative',
        icon: '🌴',
        data: {
            background: 'Neon Grid',
            era: '1980s',
            timeOfDay: 'Sunset',
            lighting: ['Neon Lights', 'Colored Gels'],
            lightColor: 'Neon Pink/Blue',
            lens: ['35mm Wide Angle'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            clothing: ['80s Neon Fashion', 'Streetwear'],
            accessories: ['Oversized Sunglasses'],
            mood: ['Retro', 'Dreamy'],
            style: ['Vaporwave', 'Retrowave'],
            colorGrading: 'Vaporwave',
            specialEffects: ['Chromatic Aberration', 'Glitch Effect', 'VHS Effect'],
            addons: ['Highly Detailed', 'Masterpiece'],
        },
    },
    {
        id: 'gothicDark',
        category: 'creative',
        icon: '🦇',
        data: {
            background: 'Gothic Cathedral',
            era: 'Victorian',
            timeOfDay: 'Night',
            weather: ['Foggy'],
            lighting: ['Low Key Lighting', 'Dramatic Shadows'],
            lightColor: 'Cool Blue',
            lens: ['50mm Standard Lens'],
            camera: 'Full Frame DSLR',
            cameraType: 'Professional DSLR',
            clothing: ['Gothic Attire', 'Victorian'],
            makeup: ['Goth/Dark'],
            accessories: ['Choker', 'Rings'],
            mood: ['Dark', 'Mysterious', 'Moody'],
            style: ['Gothic Photography', 'Dark Art'],
            colorGrading: 'Dark Moody',
            specialEffects: ['Fog', 'Vignette'],
            addons: ['Highly Detailed', 'Masterpiece', 'Cinematic'],
        },
    },
    {
        id: 'steampunkVictorian',
        category: 'creative',
        icon: '⚙️',
        data: {
            background: 'Industrial Victorian',
            era: 'Victorian',
            lighting: ['Dramatic Lighting', 'Gas Light'],
            lightColor: 'Warm Amber',
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            cameraType: 'Professional DSLR',
            clothing: ['Steampunk Attire', 'Victorian'],
            accessories: ['Goggles', 'Pocket Watch', 'Gears'],
            mood: ['Vintage', 'Industrial', 'Dramatic'],
            style: ['Steampunk Art', 'Victorian Photography'],
            colorGrading: 'Sepia',
            specialEffects: ['Steam', 'Brass Tones', 'Vignette'],
            addons: ['Highly Detailed', 'Intricate Details', 'Masterpiece'],
        },
    },
    {
        id: 'animeManga',
        category: 'creative',
        icon: '🎌',
        data: {
            background: 'Anime Background',
            lighting: ['Soft Cel-Shaded Light', 'Anime Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Digital Art',
            eyeColor: 'Large Expressive Eyes',
            hairStyle: ['Anime Hair'],
            mood: ['Energetic', 'Expressive', 'Vibrant'],
            style: ['Anime Art', 'Manga Style', 'Japanese Animation'],
            colorGrading: 'Vibrant Anime',
            specialEffects: ['Cel Shading', 'Anime Effects'],
            addons: ['Highly Detailed', '8K Resolution', 'Masterpiece', 'Anime Style'],
        },
    },
    {
        id: 'popArt',
        category: 'creative',
        icon: '🎨',
        data: {
            background: 'Bold Color Blocks',
            era: '1960s',
            lighting: ['High Key Lighting', 'Flat Lighting'],
            lens: ['50mm Standard Lens'],
            camera: 'Medium Format',
            makeup: ['Bold/Statement', 'Bright Lipstick'],
            mood: ['Bold', 'Vibrant', 'Energetic'],
            style: ['Pop Art', 'Andy Warhol Style', 'Comic Book'],
            colorGrading: 'Bold Primary Colors',
            specialEffects: ['Halftone Dots', 'Ben-Day Dots', 'High Contrast'],
            addons: ['Highly Detailed', 'Graphic Style', 'Masterpiece'],
        },
    },
    {
        id: 'filmNoir',
        category: 'creative',
        icon: '🎭',
        data: {
            background: 'Dark Alley',
            era: '1940s',
            timeOfDay: 'Night',
            weather: ['Rain'],
            lighting: ['Low Key Lighting', 'Dramatic Shadows', 'Venetian Blinds Shadow'],
            lightColor: 'Cool Blue',
            lens: ['50mm Standard Lens'],
            camera: 'Film Camera',
            cameraType: 'Vintage Film Camera',
            filmStock: ['Ilford HP5', 'Kodak Tri-X'],
            clothing: ['Trench Coat', 'Fedora'],
            mood: ['Mysterious', 'Dramatic', 'Noir'],
            style: ['Film Noir', 'Black and White Photography'],
            colorGrading: 'Black and White',
            specialEffects: ['Film Grain', 'High Contrast', 'Rain Effects'],
            addons: ['Highly Detailed', 'Cinematic', 'Masterpiece'],
        },
    },
    {
        id: 'watercolorPainting',
        category: 'creative',
        icon: '🖌️',
        data: {
            background: 'Painted Background',
            lighting: ['Soft Diffused Light', 'Natural Light'],
            mood: ['Dreamy', 'Artistic', 'Soft'],
            style: ['Watercolor Painting', 'Fine Art', 'Painted Portrait'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Watercolor Texture', 'Painted Edges', 'Soft Blending'],
            texture: ['Watercolor Paper', 'Canvas'],
            addons: ['Highly Detailed', 'Artistic', 'Masterpiece', 'Hand Painted'],
        },
    },

    // ============ UTILITY PRESETS (16) ============

    {
        id: 'qualityEnhance',
        category: 'utility',
        icon: '✨',
        data: {
            addons: ['Highly Detailed', '8K Resolution', 'Sharp Focus', 'Masterpiece', 'Professional Photography', 'Photorealistic'],
            style: ['Ultra Realistic'],
        },
    },
    {
        id: 'lightRetouch',
        category: 'utility',
        icon: '🪄',
        data: {
            makeup: ['Natural/No-Makeup Makeup', 'Dewy/Glass Skin'],
            lighting: ['Soft Natural Light', 'Diffused Lighting'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Photorealistic', 'Highly Detailed'],
        },
    },
    {
        id: 'skinPerfect',
        category: 'utility',
        icon: '💎',
        data: {
            makeup: ['Dewy/Glass Skin', 'Natural/No-Makeup Makeup', 'Heavy Highlighter/Strobing'],
            lighting: ['Beauty Dish', 'Softbox Lighting'],
            style: ['Beauty Photography'],
            addons: ['Highly Detailed', 'Sharp Focus', 'Professional Photography'],
        },
    },
    {
        id: 'hdrVivid',
        category: 'utility',
        icon: '🌈',
        data: {
            colorGrading: 'HDR',
            lighting: ['High Dynamic Range'],
            addons: ['Highly Detailed', '8K Resolution', 'HDR'],
            style: ['HDR Photography'],
        },
    },
    {
        id: 'instagramReady',
        category: 'utility',
        icon: '📱',
        data: {
            aspectRatio: '1:1 Square',
            colorGrading: 'Vibrant',
            lighting: ['Soft Natural Light'],
            addons: ['Sharp Focus', 'Highly Detailed', 'Professional Photography'],
            style: ['Lifestyle Photography'],
        },
    },
    {
        id: 'linkedinPro',
        category: 'utility',
        icon: '👔',
        data: {
            background: 'Neutral Gray',
            pose: ['Headshot', 'Front Facing Portrait'],
            lighting: ['Studio Lighting', 'Softbox Lighting'],
            colorGrading: 'Natural',
            addons: ['Sharp Focus', 'Professional Photography', 'Highly Detailed'],
            style: ['Corporate Photography'],
        },
    },
    {
        id: 'softDreamy',
        category: 'utility',
        icon: '☁️',
        data: {
            lighting: ['Soft Natural Light', 'Backlight'],
            colorGrading: 'Soft Pastel',
            specialEffects: ['Soft Glow', 'Bokeh'],
            mood: ['Dreamy', 'Romantic'],
            addons: ['Highly Detailed', 'Photorealistic'],
        },
    },
    {
        id: 'sharpDetail',
        category: 'utility',
        icon: '🔍',
        data: {
            lens: ['Macro Lens'],
            composition: ['Close-up', 'Center Composition'],
            addons: ['Sharp Focus', 'Highly Detailed', '8K Resolution', 'Intricate Details'],
            style: ['Macro Photography'],
        },
    },
    {
        id: 'instantPro',
        category: 'utility',
        icon: '📸',
        data: {
            lens: ['85mm Portrait Lens'],
            camera: 'Mirrorless',
            cameraType: 'Professional DSLR',
            lighting: ['Softbox Lighting', 'Studio Lighting'],
            addons: ['Professional Photography', 'Highly Detailed', 'Masterpiece', '8K Resolution', 'Sharp Focus'],
            style: ['Professional Photography'],
        },
    },
    {
        id: 'hairPerfect',
        category: 'utility',
        icon: '💇‍♀️',
        data: {
            addons: ['Voluminous Hair', 'Detailed Hair Texture', 'Perfectly Styled Hair', 'Shiny Hair', 'High Quality'],
            lighting: ['Rim Lighting', 'Backlight'],
        },
    },
    {
        id: 'lightingFix',
        category: 'utility',
        icon: '💡',
        data: {
            lighting: ['Soft Natural Light', 'Diffused Lighting', 'Cinematic Lighting'],
            addons: ['Perfect Exposure', 'Balanced Lighting', 'Professional Lighting'],
        },
    },
    {
        id: 'outfitDetail',
        category: 'utility',
        icon: '👗',
        data: {
            addons: ['Detailed Fabric Texture', 'Intricate Patterns', 'High Quality Materials', 'Sharp Focus'],
            lighting: ['Studio Lighting'],
            cameraType: 'Professional DSLR',
        },
    },
    {
        id: 'backgroundBlur',
        category: 'utility',
        icon: '🌫️',
        data: {
            lens: ['85mm Portrait Lens', '50mm Standard Lens'],
            composition: ['Shallow Depth of Field', 'Center Composition'],
            specialEffects: ['Bokeh', 'Creamy Bokeh'],
            addons: ['Sharp Subject Focus', 'Soft Background', 'Professional Bokeh'],
            style: ['Portrait Photography'],
        },
    },
    {
        id: 'colorPop',
        category: 'utility',
        icon: '🔴',
        data: {
            colorGrading: 'Selective Color',
            specialEffects: ['Selective Color Highlight'],
            addons: ['Highly Detailed', 'Vibrant Accent Color', 'Black and White Background'],
            style: ['Creative Photography'],
        },
    },
    {
        id: 'eyeEnhance',
        category: 'utility',
        icon: '👁️',
        data: {
            eyeColor: 'Vibrant Eye Color',
            lighting: ['Catchlight', 'Beauty Dish'],
            addons: ['Sparkling Eyes', 'Detailed Iris', 'Sharp Eye Focus', 'Enhanced Eye Color'],
            style: ['Beauty Photography'],
        },
    },
    {
        id: 'symmetryFix',
        category: 'utility',
        icon: '⚖️',
        data: {
            composition: ['Center Composition', 'Symmetrical Framing'],
            pose: ['Front Facing Portrait', 'Straight Angle'],
            addons: ['Perfect Symmetry', 'Balanced Features', 'Professional Photography'],
            lighting: ['Even Lighting', 'Softbox Lighting'],
        },
    },
];

// Helper to get presets by category
export const getPresetsByCategory = (category: 'common' | 'creative'): Preset[] => {
    return presets.filter((p) => p.category === category);
};

// Helper to get a preset by ID
export const getPresetById = (id: string): Preset | undefined => {
    return presets.find((p) => p.id === id);
};
